version: '3.8'

services:
  # --- 5 LAYANAN APLIKASI ASLI ---

  vote:
    build: ./vote
    # PERBAIKAN: Kita menghapus 'target: dev'
    expose:
      - "8000"
    ports:
      - "5000:80"
    networks:
      - vote-net
    labels:
      - "app=vote"

  redis:
    image: redis:alpine
    networks:
      - vote-net

  worker:
    build: ./worker
    depends_on:
      - db
      - redis
    networks:
      - vote-net
    labels:
      - "app=worker"

  db:
    image: postgres:9.4
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    networks:
      - vote-net
    labels:
      - "app=db"

  result:
    build: ./result
    ports:
      - "5001:80"
    depends_on:
      - db
    networks:
      - vote-net
    labels:
      - "app=result"

  # --- 4 LAYANAN MONITORING BARU ---

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - vote-net
    labels:
      - "app=prometheus"

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    depends_on:
      - prometheus
      - loki
    networks:
      - vote-net
    labels:
      - "app=grafana"

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - vote-net
    labels:
      - "app=loki"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail:/etc/promtail
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yml
    depends_on:
      - loki
    networks:
      - vote-net
    labels:
      - "app=promtail"

# --- DEFINISI NETWORKS & VOLUMES ---

networks:
  vote-net:

volumes:
  db-data:
  grafana-data: